// Major Minecraft releases. Focused on headline updates only.
const MINECRAFT_VERSIONS = [
  {
    version: "Classic",
    codename: "Cave Game",
    year: 2009,
    date: "2009-05-17",
    era: "pre",
    headline: "The beginning — creative block-placing demo.",
    features: [
      "Infinite block placing/breaking",
      "Multiplayer browser prototype",
      "Only a handful of block types",
    ],
    worldHeight: 64,
    newDimension: null,
    tags: ["Alpha", "Prototype"],
  },
  {
    version: "Indev / Infdev",
    codename: "Survival Test",
    year: 2010,
    date: "2010-02-23",
    era: "pre",
    headline: "Survival is born — monsters, crafting, and caves appear.",
    features: [
      "Health, mobs, and hunger origins",
      "Crafting table & smelting",
      "Infinite worlds (Infdev)",
    ],
    worldHeight: 128,
    newDimension: null,
    tags: ["Survival", "Crafting"],
  },
  {
    version: "Alpha 1.2",
    codename: "Halloween Update",
    year: 2010,
    date: "2010-10-31",
    era: "pre",
    headline: "The Nether, biomes, and lighting arrive.",
    features: [
      "The Nether dimension",
      "Biomes & new weather",
      "Fishing, clocks, note blocks",
    ],
    worldHeight: 128,
    newDimension: "The Nether",
    tags: ["Nether", "Biomes"],
  },
  {
    version: "Beta 1.8",
    codename: "Adventure Update",
    year: 2011,
    date: "2011-09-14",
    era: "pre",
    headline: "Hunger, sprinting, and the first structures.",
    features: [
      "Hunger bar & food mechanics",
      "Villages, strongholds, abandoned mineshafts",
      "New terrain generation",
    ],
    worldHeight: 128,
    newDimension: null,
    tags: ["Exploration", "Villages"],
  },
  {
    version: "1.0",
    codename: "Adventure Update Pt. 2",
    year: 2011,
    date: "2011-11-18",
    era: "classic",
    headline: "Full release! The End and the Ender Dragon.",
    features: [
      "The End + Ender Dragon boss",
      "Enchanting table & brewing stands",
      "Official 1.0 launch at MineCon",
    ],
    worldHeight: 128,
    newDimension: "The End",
    tags: ["Launch", "Boss"],
  },
  {
    version: "1.2",
    codename: "",
    year: 2012,
    date: "2012-03-01",
    era: "classic",
    headline: "Taller worlds and jungle biomes.",
    features: [
      "World height raised to 256",
      "Jungle biome + ocelots",
      "Iron Golems & villager AI",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Jungle", "Height"],
  },
  {
    version: "1.3",
    codename: "",
    year: 2012,
    date: "2012-08-01",
    era: "classic",
    headline: "Trading, emeralds, and single-player LAN.",
    features: [
      "Villager trading with emeralds",
      "Tripwires & ender chests",
      "LAN multiplayer from singleplayer",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Trading"],
  },
  {
    version: "1.4",
    codename: "Pretty Scary Update",
    year: 2012,
    date: "2012-10-25",
    era: "classic",
    headline: "Witches, wither, and a head full of trouble.",
    features: [
      "The Wither boss + Nether Star",
      "Witches & witch huts",
      "Beacons and mob heads",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Boss", "Spooky"],
  },
  {
    version: "1.5",
    codename: "Redstone Update",
    year: 2013,
    date: "2013-03-13",
    era: "classic",
    headline: "Redstone gets a massive upgrade.",
    features: [
      "Redstone comparators & hoppers",
      "Droppers & daylight sensors",
      "Quartz blocks from the Nether",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Redstone"],
  },
  {
    version: "1.6",
    codename: "Horse Update",
    year: 2013,
    date: "2013-07-01",
    era: "classic",
    headline: "Horses, leads, and the new launcher.",
    features: [
      "Horses, donkeys & mules",
      "Leads & carpets",
      "New Minecraft launcher with profiles",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Mobs"],
  },
  {
    version: "1.7",
    codename: "The Update That Changed The World",
    year: 2013,
    date: "2013-10-25",
    era: "classic",
    headline: "A complete overhaul of biomes.",
    features: [
      "Dozens of new biomes (mesa, savanna, roofed forest)",
      "Amplified world type",
      "Stained glass & new flowers",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Biomes", "World-gen"],
  },
  {
    version: "1.8",
    codename: "Bountiful Update",
    year: 2014,
    date: "2014-09-02",
    era: "classic",
    headline: "Oceans deepen and stone gets stylish.",
    features: [
      "Ocean monuments + guardians",
      "Slime blocks, banners, armor stands",
      "Granite, diorite, andesite",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Oceans", "Building"],
  },
  {
    version: "1.9",
    codename: "Combat Update",
    year: 2016,
    date: "2016-02-29",
    era: "modern",
    headline: "Combat gets a cooldown — and shields.",
    features: [
      "Attack cooldown & dual-wielding",
      "Shields replace blocking with swords",
      "End cities, ships, and the elytra",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Combat", "Elytra"],
  },
  {
    version: "1.10",
    codename: "Frostburn Update",
    year: 2016,
    date: "2016-06-08",
    era: "modern",
    headline: "Polar bears, magma, and strays.",
    features: [
      "Polar bears & husks & strays",
      "Magma blocks & nether fossils",
      "Auto-jump feature",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Mobs"],
  },
  {
    version: "1.11",
    codename: "Exploration Update",
    year: 2016,
    date: "2016-11-14",
    era: "modern",
    headline: "Woodland mansions and llamas.",
    features: [
      "Woodland mansions + illagers",
      "Llamas, vexes, evokers",
      "Shulker boxes & totems of undying",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Exploration"],
  },
  {
    version: "1.12",
    codename: "World of Color",
    year: 2017,
    date: "2017-06-07",
    era: "modern",
    headline: "Concrete, parrots, and crafting advancements.",
    features: [
      "Concrete & glazed terracotta",
      "Parrots & recipe book",
      "Advancements replace achievements",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Color", "Building"],
  },
  {
    version: "1.13",
    codename: "Update Aquatic",
    year: 2018,
    date: "2018-07-18",
    era: "modern",
    headline: "Oceans rebuilt from the seabed up.",
    features: [
      "Dolphins, turtles, fish, coral reefs",
      "Tridents and conduits",
      "Massive technical rewrite (Flattening)",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Oceans"],
  },
  {
    version: "1.14",
    codename: "Village & Pillage",
    year: 2019,
    date: "2019-04-23",
    era: "modern",
    headline: "Villages reimagined, pillagers added.",
    features: [
      "Redesigned villages by biome",
      "Pillager raids & pillage outposts",
      "Bamboo, pandas, foxes, cats",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Villages", "Raids"],
  },
  {
    version: "1.15",
    codename: "Buzzy Bees",
    year: 2019,
    date: "2019-12-10",
    era: "modern",
    headline: "Bees, beehives, and bug fixes.",
    features: [
      "Bees, beehives, honey blocks",
      "Honey bottles & honeycomb",
      "Major performance + bug fix pass",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Bees"],
  },
  {
    version: "1.16",
    codename: "Nether Update",
    year: 2020,
    date: "2020-06-23",
    era: "modern",
    headline: "The Nether becomes a world of its own.",
    features: [
      "Nether biomes (Crimson Forest, Soul Sand Valley…)",
      "Piglins, hoglins & striders",
      "Netherite tools and armor",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Nether", "Netherite"],
  },
  {
    version: "1.17",
    codename: "Caves & Cliffs Pt. 1",
    year: 2021,
    date: "2021-06-08",
    era: "current",
    headline: "Goats, axolotls, and glowing squids.",
    features: [
      "Amethyst geodes & tinted glass",
      "Axolotls, goats, glow squid",
      "Copper + lightning rods",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Mobs", "Caves"],
  },
  {
    version: "1.18",
    codename: "Caves & Cliffs Pt. 2",
    year: 2021,
    date: "2021-11-30",
    era: "current",
    headline: "Worlds get taller and caves get huge.",
    features: [
      "World height raised to 384 (−64 to 320)",
      "Dripstone, lush, and massive caves",
      "Rewritten world generation",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Caves", "World-gen"],
  },
  {
    version: "1.19",
    codename: "The Wild Update",
    year: 2022,
    date: "2022-06-07",
    era: "current",
    headline: "Deep Dark, Warden, and a new biome swampland.",
    features: [
      "The Deep Dark & Ancient Cities",
      "The Warden, sculk blocks",
      "Allay, frogs, tadpoles, mangrove swamps",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Deep Dark", "Warden"],
  },
  {
    version: "1.20",
    codename: "Trails & Tales",
    year: 2023,
    date: "2023-06-07",
    era: "current",
    headline: "Archaeology, camels, and cherry blossoms.",
    features: [
      "Archaeology with brushes & pottery shards",
      "Camels, sniffers, cherry groves",
      "Smithing templates & armor trims",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Archaeology", "Customization"],
  },
  {
    version: "1.21",
    codename: "Tricky Trials",
    year: 2024,
    date: "2024-06-13",
    era: "current",
    headline: "Trial chambers, maces, and new mobs.",
    features: [
      "Trial chambers & vaults",
      "The Breeze & Bogged mobs",
      "Mace weapon with smash attacks",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Combat", "Dungeons"],
  },
  {
    version: "1.22",
    codename: "Copper Age",
    year: 2025,
    date: "2025-09-30",
    era: "current",
    headline: "Copper tools, new biomes, and bundles.",
    features: [
      "Copper tools, armor, and golems",
      "Expanded copper decorative blocks",
      "Bundles fully released",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Copper", "Tools"],
  },
];
