// Major Minecraft releases. Focused on headline updates only.
const MINECRAFT_VERSIONS = [
  {
    version: "Classic",
    codename: "Cave Game",
    year: 2009,
    date: "2009-05-17",
    era: "pre",
    headline: "The beginning — creative block-placing demo.",
    features: [
      "Infinite block placing/breaking",
      "Multiplayer browser prototype",
      "Only a handful of block types",
    ],
    worldHeight: 64,
    newDimension: null,
    tags: ["Alpha", "Prototype"],
    icon: "🧱",
    palette: { sky1: "#9aa0a6", sky2: "#cfd2d6", g1: "#6e6e6e", g2: "#3a3a3a" },
  },
  {
    version: "Indev / Infdev",
    codename: "Survival Test",
    year: 2010,
    date: "2010-02-23",
    era: "pre",
    headline: "Survival is born — monsters, crafting, and caves appear.",
    features: [
      "Health, mobs, and hunger origins",
      "Crafting table & smelting",
      "Infinite worlds (Infdev)",
    ],
    worldHeight: 128,
    newDimension: null,
    tags: ["Survival", "Crafting"],
    icon: "⛏️",
    palette: { sky1: "#6a5a48", sky2: "#a48a6a", g1: "#5a4030", g2: "#2a1a10" },
  },
  {
    version: "Alpha 1.2",
    codename: "Halloween Update",
    year: 2010,
    date: "2010-10-31",
    era: "pre",
    headline: "The Nether, biomes, and lighting arrive.",
    features: [
      "The Nether dimension",
      "Biomes & new weather",
      "Fishing, clocks, note blocks",
    ],
    worldHeight: 128,
    newDimension: "The Nether",
    tags: ["Nether", "Biomes"],
    icon: "👻",
    palette: { sky1: "#2a1512", sky2: "#6a1a12", g1: "#4a1818", g2: "#1a0808" },
  },
  {
    version: "Beta 1.8",
    codename: "Adventure Update",
    year: 2011,
    date: "2011-09-14",
    era: "pre",
    headline: "Hunger, sprinting, and the first structures.",
    features: [
      "Hunger bar & food mechanics",
      "Villages, strongholds, abandoned mineshafts",
      "New terrain generation",
    ],
    worldHeight: 128,
    newDimension: null,
    tags: ["Exploration", "Villages"],
    icon: "🗺️",
    palette: { sky1: "#87ceeb", sky2: "#c8e6ff", g1: "#6a4a28", g2: "#3e2a18" },
  },
  {
    version: "1.0",
    codename: "Adventure Update Pt. 2",
    year: 2011,
    date: "2011-11-18",
    era: "classic",
    headline: "Full release! The End and the Ender Dragon.",
    features: [
      "The End + Ender Dragon boss",
      "Enchanting table & brewing stands",
      "Official 1.0 launch at MineCon",
    ],
    worldHeight: 128,
    newDimension: "The End",
    tags: ["Launch", "Boss"],
    icon: "🐉",
    palette: { sky1: "#1a0f2a", sky2: "#4a2a6a", g1: "#d8d19a", g2: "#8a8260" },
  },
  {
    version: "1.2",
    codename: "",
    year: 2012,
    date: "2012-03-01",
    era: "classic",
    headline: "Taller worlds and jungle biomes.",
    features: [
      "World height raised to 256",
      "Jungle biome + ocelots",
      "Iron Golems & villager AI",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Jungle", "Height"],
    icon: "🌴",
    palette: { sky1: "#9fe0a3", sky2: "#5ab552", g1: "#2f6b2b", g2: "#183e15" },
  },
  {
    version: "1.3",
    codename: "",
    year: 2012,
    date: "2012-08-01",
    era: "classic",
    headline: "Trading, emeralds, and single-player LAN.",
    features: [
      "Villager trading with emeralds",
      "Tripwires & ender chests",
      "LAN multiplayer from singleplayer",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Trading"],
    icon: "💎",
    palette: { sky1: "#b0e890", sky2: "#6fc75f", g1: "#3a6b3a", g2: "#1f3a1f" },
  },
  {
    version: "1.4",
    codename: "Pretty Scary Update",
    year: 2012,
    date: "2012-10-25",
    era: "classic",
    headline: "Witches, wither, and a head full of trouble.",
    features: [
      "The Wither boss + Nether Star",
      "Witches & witch huts",
      "Beacons and mob heads",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Boss", "Spooky"],
    icon: "🎃",
    palette: { sky1: "#2a1a2a", sky2: "#6a3018", g1: "#c06818", g2: "#4a1e10" },
  },
  {
    version: "1.5",
    codename: "Redstone Update",
    year: 2013,
    date: "2013-03-13",
    era: "classic",
    headline: "Redstone gets a massive upgrade.",
    features: [
      "Redstone comparators & hoppers",
      "Droppers & daylight sensors",
      "Quartz blocks from the Nether",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Redstone"],
    icon: "🔴",
    palette: { sky1: "#c1292e", sky2: "#7a1518", g1: "#5a1a1a", g2: "#1a0808" },
    banner: "Redstone Update.png",
  },
  {
    version: "1.6",
    codename: "Horse Update",
    year: 2013,
    date: "2013-07-01",
    era: "classic",
    headline: "Horses, leads, and the new launcher.",
    features: [
      "Horses, donkeys & mules",
      "Leads & carpets",
      "New Minecraft launcher with profiles",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Mobs"],
    icon: "🐴",
    palette: { sky1: "#b5cf7a", sky2: "#7ea84c", g1: "#6b4a2a", g2: "#3a2818" },
    banner: "Horse Update.png",
  },
  {
    version: "1.7",
    codename: "The Update That Changed The World",
    year: 2013,
    date: "2013-10-25",
    era: "classic",
    headline: "A complete overhaul of biomes.",
    features: [
      "Dozens of new biomes (mesa, savanna, roofed forest)",
      "Amplified world type",
      "Stained glass & new flowers",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Biomes", "World-gen"],
    icon: "🌈",
    palette: { sky1: "#ffd27a", sky2: "#88c4ff", g1: "#3a8a3a", g2: "#6a4628" },
    banner: "The Update that Changed the World.png",
  },
  {
    version: "1.8",
    codename: "Bountiful Update",
    year: 2014,
    date: "2014-09-02",
    era: "classic",
    headline: "Oceans deepen and stone gets stylish.",
    features: [
      "Ocean monuments + guardians",
      "Slime blocks, banners, armor stands",
      "Granite, diorite, andesite",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Oceans", "Building"],
    icon: "🐟",
    palette: { sky1: "#88c4ff", sky2: "#2b6dbf", g1: "#1a3a6a", g2: "#0a1a3a" },
    banner: "Bountiful Update.png",
  },
  {
    version: "1.9",
    codename: "Combat Update",
    year: 2016,
    date: "2016-02-29",
    era: "modern",
    headline: "Combat gets a cooldown — and shields.",
    features: [
      "Attack cooldown & dual-wielding",
      "Shields replace blocking with swords",
      "End cities, ships, and the elytra",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Combat", "Elytra"],
    icon: "⚔️",
    palette: { sky1: "#1a0f2a", sky2: "#3a2a5a", g1: "#b09e7a", g2: "#5a4a30" },
    banner: "Combat Update.png",
  },
  {
    version: "1.10",
    codename: "Frostburn Update",
    year: 2016,
    date: "2016-06-08",
    era: "modern",
    headline: "Polar bears, magma, and strays.",
    features: [
      "Polar bears & husks & strays",
      "Magma blocks & nether fossils",
      "Auto-jump feature",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Mobs"],
    icon: "🐻‍❄️",
    palette: { sky1: "#cfe8ff", sky2: "#8fb8e8", g1: "#e0e9f2", g2: "#a8b8c8" },
    banner: "Frostburn Update.png",
  },
  {
    version: "1.11",
    codename: "Exploration Update",
    year: 2016,
    date: "2016-11-14",
    era: "modern",
    headline: "Woodland mansions and llamas.",
    features: [
      "Woodland mansions + illagers",
      "Llamas, vexes, evokers",
      "Shulker boxes & totems of undying",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Exploration"],
    icon: "🏰",
    palette: { sky1: "#2a2e3a", sky2: "#4a5260", g1: "#6e4a2a", g2: "#3a2818" },
    banner: "Exploration Update.png",
  },
  {
    version: "1.12",
    codename: "World of Color",
    year: 2017,
    date: "2017-06-07",
    era: "modern",
    headline: "Concrete, parrots, and crafting advancements.",
    features: [
      "Concrete & glazed terracotta",
      "Parrots & recipe book",
      "Advancements replace achievements",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Color", "Building"],
    icon: "🎨",
    palette: { sky1: "#ffbfd8", sky2: "#b0a0ff", g1: "#70c88a", g2: "#2a6a4a" },
    banner: "World of Color Update.png",
  },
  {
    version: "1.13",
    codename: "Update Aquatic",
    year: 2018,
    date: "2018-07-18",
    era: "modern",
    headline: "Oceans rebuilt from the seabed up.",
    features: [
      "Dolphins, turtles, fish, coral reefs",
      "Tridents and conduits",
      "Massive technical rewrite (Flattening)",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Oceans"],
    icon: "🐬",
    palette: { sky1: "#a8e0ff", sky2: "#2b8fbf", g1: "#124a6a", g2: "#06243a" },
    banner: "Update Aquatic.png",
  },
  {
    version: "1.14",
    codename: "Village & Pillage",
    year: 2019,
    date: "2019-04-23",
    era: "modern",
    headline: "Villages reimagined, pillagers added.",
    features: [
      "Redesigned villages by biome",
      "Pillager raids & pillage outposts",
      "Bamboo, pandas, foxes, cats",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Villages", "Raids"],
    icon: "🛖",
    palette: { sky1: "#c9e0a0", sky2: "#8ab560", g1: "#8a5a2e", g2: "#4a2e18" },
    banner: "Village & Pillage.png",
  },
  {
    version: "1.15",
    codename: "Buzzy Bees",
    year: 2019,
    date: "2019-12-10",
    era: "modern",
    headline: "Bees, beehives, and bug fixes.",
    features: [
      "Bees, beehives, honey blocks",
      "Honey bottles & honeycomb",
      "Major performance + bug fix pass",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Bees"],
    icon: "🐝",
    palette: { sky1: "#ffe89a", sky2: "#f0b24a", g1: "#5a8a2a", g2: "#2a4a15" },
    banner: "Buzzy Bees.png",
  },
  {
    version: "1.16",
    codename: "Nether Update",
    year: 2020,
    date: "2020-06-23",
    era: "modern",
    headline: "The Nether becomes a world of its own.",
    features: [
      "Nether biomes (Crimson Forest, Soul Sand Valley…)",
      "Piglins, hoglins & striders",
      "Netherite tools and armor",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Nether", "Netherite"],
    icon: "🔥",
    palette: { sky1: "#6a1818", sky2: "#c13018", g1: "#3a0a0a", g2: "#1a0202" },
    banner: "Nether Update.png",
  },
  {
    version: "1.17",
    codename: "Caves & Cliffs Pt. 1",
    year: 2021,
    date: "2021-06-08",
    era: "current",
    headline: "Goats, axolotls, and glowing squids.",
    features: [
      "Amethyst geodes & tinted glass",
      "Axolotls, goats, glow squid",
      "Copper + lightning rods",
    ],
    worldHeight: 256,
    newDimension: null,
    tags: ["Mobs", "Caves"],
    icon: "🦎",
    palette: { sky1: "#ffb0c8", sky2: "#ef6a9a", g1: "#7a4a88", g2: "#3a1e4a" },
    banner: "Caves & Cliffs.png",
  },
  {
    version: "1.18",
    codename: "Caves & Cliffs Pt. 2",
    year: 2021,
    date: "2021-11-30",
    era: "current",
    headline: "Worlds get taller and caves get huge.",
    features: [
      "World height raised to 384 (−64 to 320)",
      "Dripstone, lush, and massive caves",
      "Rewritten world generation",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Caves", "World-gen"],
    icon: "🕳️",
    palette: { sky1: "#3a3630", sky2: "#6a5e50", g1: "#2a2622", g2: "#0e0c08" },
    banner: "Caves & Cliffs.png",
  },
  {
    version: "1.19",
    codename: "The Wild Update",
    year: 2022,
    date: "2022-06-07",
    era: "current",
    headline: "Deep Dark, Warden, and a new biome swampland.",
    features: [
      "The Deep Dark & Ancient Cities",
      "The Warden, sculk blocks",
      "Allay, frogs, tadpoles, mangrove swamps",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Deep Dark", "Warden"],
    icon: "🐸",
    palette: { sky1: "#0a2a3a", sky2: "#1a5e6a", g1: "#0a3a2a", g2: "#04180e" },
    banner: "The Wild Update.png",
  },
  {
    version: "1.20",
    codename: "Trails & Tales",
    year: 2023,
    date: "2023-06-07",
    era: "current",
    headline: "Archaeology, camels, and cherry blossoms.",
    features: [
      "Archaeology with brushes & pottery shards",
      "Camels, sniffers, cherry groves",
      "Smithing templates & armor trims",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Archaeology", "Customization"],
    icon: "🌸",
    palette: { sky1: "#ffd8e8", sky2: "#ff9ab8", g1: "#b86a80", g2: "#5e2e3e" },
    banner: "Trails & Tales.png",
  },
  {
    version: "1.21",
    codename: "Tricky Trials",
    year: 2024,
    date: "2024-06-13",
    era: "current",
    headline: "Trial chambers, maces, and new mobs.",
    features: [
      "Trial chambers & vaults",
      "The Breeze & Bogged mobs",
      "Mace weapon with smash attacks",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Combat", "Dungeons"],
    icon: "🗝️",
    palette: { sky1: "#ffd06a", sky2: "#c08830", g1: "#5a4018", g2: "#1a1008" },
    banner: "Tricky Trials.png",
  },
  {
    version: "1.22",
    codename: "Copper Age",
    year: 2025,
    date: "2025-09-30",
    era: "current",
    headline: "Copper tools, new biomes, and bundles.",
    features: [
      "Copper tools, armor, and golems",
      "Expanded copper decorative blocks",
      "Bundles fully released",
    ],
    worldHeight: 384,
    newDimension: null,
    tags: ["Copper", "Tools"],
    icon: "🟠",
    palette: { sky1: "#ffc28a", sky2: "#d97840", g1: "#8a4a2a", g2: "#3a1e10" },
  },
];
